### ISSUE TITLE
venv directory still exists despite being included in gitignore

### ISSUE THREAD

**Issue by michalirak** [GoodbyeBlues/article-summarizer#2]
Best to delete it from the repository.
If you would like help, please make sure to assign me so that I know to take care of it :)

**Comment by GoodbyeBlues** [comment]
For sure. If you could, let me know what the problem is too cause i really just don't get why it's still here. Just labeled it with Hacktoberfest for you.

**Comment by vivax3794** [comment]
oh adding something to .gitignore after it has already been committed does not remove it, I can fix it and open a pr.

**Comment by michalirak** [comment]
Great work from @vivax3794.
I would also recommend shortening the .gitignore.
Currently working on a PR for that :)
